In [2]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns = ['A','B','C'],index = ['x','y','z'])

In [5]:
df.tail()
df.info()
df.describe()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [6]:
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
coffee.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [4]:
coffee.sample(9)

         Day Coffee Type  Units Sold
12    Sunday    Espresso          45
7   Thursday       Latte          30
13    Sunday       Latte          35
0     Monday    Espresso          25
3    Tuesday       Latte          20
10  Saturday    Espresso          45
11  Saturday       Latte          35
6   Thursday    Espresso          40
9     Friday       Latte          35

In [5]:
coffee.describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [5]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [7]:
coffee.loc[1,"Coffee Type"] = "Chai"

In [8]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday        Chai          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [11]:
coffee.iat[2,1]

'Espresso'

In [9]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [10]:
coffee["Units Sold"]

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [11]:
coffee["Coffee Type"]

0     Espresso
1         Chai
2     Espresso
3        Latte
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: str

In [17]:
for index,row in coffee.iterrows():
    print(f"{index}\n{row}\n\n\n")

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object



1
Day            Monday
Coffee Type      Chai
Units Sold         15
Name: 1, dtype: object



2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object



3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object



4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object



5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object



6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object



7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object



8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object



9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object



10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object



11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object



12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object



13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

In [19]:
coffee.loc[coffee["Units Sold"]>35,["Coffee Type","Units Sold"]]

   Coffee Type  Units Sold
6     Espresso          40
8     Espresso          45
10    Espresso          45
12    Espresso          45

In [14]:
coffee.loc[[9,10]][["Day","Units Sold"]]

         Day  Units Sold
9     Friday          35
10  Saturday          45

In [17]:
#conditions
coffee[(coffee["Coffee Type"]=="Latte") & (coffee["Units Sold"]<35)]

         Day Coffee Type  Units Sold
1     Monday       Latte          15
3    Tuesday       Latte          20
5  Wednesday       Latte          25
7   Thursday       Latte          30

In [7]:
coffee.set_index("Day")

          Coffee Type  Units Sold
Day
Monday       Espresso          25
Monday          Latte          15
Tuesday      Espresso          30
Tuesday         Latte          20
Wednesday    Espresso          35
Wednesday       Latte          25
Thursday     Espresso          40
Thursday        Latte          30
Friday       Espresso          45
Friday          Latte          35
Saturday     Espresso          45
Saturday        Latte          35
Sunday       Espresso          45
Sunday          Latte          35

In [9]:
coffee.reset_index()

    index        Day Coffee Type  Units Sold
0       0     Monday    Espresso          25
1       1     Monday       Latte          15
2       2    Tuesday    Espresso          30
3       3    Tuesday       Latte          20
4       4  Wednesday    Espresso          35
5       5  Wednesday       Latte          25
6       6   Thursday    Espresso          40
7       7   Thursday       Latte          30
8       8     Friday    Espresso          45
9       9     Friday       Latte          35
10     10   Saturday    Espresso          45
11     11   Saturday       Latte          35
12     12     Sunday    Espresso          45
13     13     Sunday       Latte          35